language: java
jdk:
  - oraclejdk8

services:
  - docker

after_success:
  - echo $CANISTER_DOCKER_USERNAME
  - docker login --username=$CANISTER_DOCKER_USERNAME --password=$CANISTER_DOCKER_PASSWORD cloud.canister.io:5000
  - docker build -t test-travis .